veterinary.Web/Controllers/MedicationController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Veterinary.DAL;
using Veterinary.Model;

namespace Veterinary.Web.Controllers
{
    public class MedicationController : BaseController
    {

        private VeterinaryManagerDbContext veterinaryManagerDbContext;
        private UserManager<AppUser> _userManager;

        public MedicationController(VeterinaryManagerDbContext veterinaryManagerDbContext, UserManager<AppUser> _userManager) : base(_userManager)
        {
            this.veterinaryManagerDbContext = veterinaryManagerDbContext;
            this._userManager = _userManager;
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpGet]
        public IActionResult Index()
        {
            var medication = veterinaryManagerDbContext.Medication.ToList();

            return View(medication.ToList());
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpPost]

        public IActionResult Create(Medication medication)
        {
            if(ModelState.IsValid)
            {
                veterinaryManagerDbContext.Medication.Add(medication);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medication);
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [ActionName("Edit")]
        public IActionResult EditGet(int id)
        {
            var medication = veterinaryManagerDbContext.Medication.First(m => m.ID == id);

            return View(medication);
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> EditPost(int id)
        {
            var medication = veterinaryManagerDbContext.Medication.First(m => m.ID == id);

            bool isOk = await TryUpdateModelAsync(medication);

            var validationErrors = ModelState.Values.Where(E => E.Errors.Count > 0)
                .SelectMany(E => E.Errors)
                .Select(E => E.ErrorMessage)
                .ToList();


            if (isOk)
            {
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }
    }
}

veterinary.Web/Controllers/OwnerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Veterinary.DAL;
using Veterinary.Model;

namespace Veterinary.Web.Controllers
{
    public class OwnerController : BaseController
    {

        private VeterinaryManagerDbContext veterinaryManagerDbContext;
        private UserManager<AppUser> _userManager;

        public OwnerController(VeterinaryManagerDbContext veterinaryManagerDbContext, UserManager<AppUser> _userManager) : base(_userManager)
        {
            this.veterinaryManagerDbContext = veterinaryManagerDbContext;
            this._userManager = _userManager;
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpGet]
        public IActionResult Index()
        {
            var owners = veterinaryManagerDbContext.Owners.ToList();

            return View(owners.ToList());
        }


        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpPost]
        public IActionResult Create(Owner owner)
        {
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Owners.Add(owner);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(owner);
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [ActionName("Edit")]
        public IActionResult EditGet(int id)
        {
            var owner = veterinaryManagerDbContext.Owners.First(m => m.ID == id);

            return View(owner);
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> EditPost(int id)
        {
            var owner = veterinaryManagerDbContext.Owners.First(m => m.ID == id);

            bool isOk = await TryUpdateModelAsync(owner);

            var validationErrors = ModelState.Values.Where(E => E.Errors.Count > 0)
                .SelectMany(E => E.Errors)
                .Select(E => E.ErrorMessage)
                .ToList();


            if (isOk)
            {
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }


        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult Delete(int id)
        {
            var existingOwner = veterinaryManagerDbContext.Owners.First(o => o.ID == id);

            if(existingOwner == null)
            {
                return NotFound();
            }

            veterinaryManagerDbContext.Owners.Remove(existingOwner);
            veterinaryManagerDbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

veterinary.Web/Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using Veterinary.DAL;
using Veterinary.Model;
using Veterinary.Web.Models;

namespace Veterinary.Web.Controllers
{
    public class PetController : BaseController
    {

        private VeterinaryManagerDbContext veterinaryManagerDbContext;
        private UserManager<AppUser> _userManager;

        public PetController(VeterinaryManagerDbContext veterinaryManagerDbContext, UserManager<AppUser> _userManager) :base(_userManager) { 
            this.veterinaryManagerDbContext = veterinaryManagerDbContext;
            this._userManager = _userManager;
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult Index()
        {
            var pets = veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .ToList();

            return View(pets.ToList());
        }


        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult IndexAjax(PetFilterModel petFilterModel)
        {
            var pets = veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .ToList();


            var filteredPets = FilterPets(pets, petFilterModel);

            return PartialView("_IndexTable", filteredPets.ToList());
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpPost]
        public IActionResult Filter(PetFilterModel petFilterModel)
        {
            var pets = veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .ToList();

            var filteredPets = FilterPets(pets, petFilterModel);

            return View("Index", pets.ToList());
        }


        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult Details(int? id)
        {
            var pet = id != null ? veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .Where(p => p.ID == id)
                .FirstOrDefault() : null;

            var prescriptions = veterinaryManagerDbContext.Prescriptions
                .Include(pr => pr.Medications)
                .Include(pr => pr.Pet)
                .Where(pr => pr.PetID == id)
                .ToList();

            ViewBag.Prescriptions = prescriptions.ToList();

            return View(pet);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        public IActionResult Create(string species)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();

            Pet pet;
            if(species == "Dog")
            {
                pet = new Dog();
            }
            else if(species == "Bird")
            {
                pet = new Bird();
            }
            else
            {
                pet = new Hamster();
            }

            return View(pet);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        public IActionResult CreateDog(Dog dog)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Pets.Add(dog);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(dog);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        public IActionResult CreateBird(Bird bird)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Pets.Add(bird);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(bird);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        public IActionResult CreateHamster(Hamster hamster)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Pets.Add(hamster);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(hamster);
        }


        [Authorize(Roles = RoleConstants.Doctor)]
        [ActionName("Edit")]
        public IActionResult EditGet(int id)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();

            var pet = veterinaryManagerDbContext.Pets.First(p => p.ID == id);

            return View(pet);
        }


        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> EditPost(int id)
        {
            var pet = veterinaryManagerDbContext.Pets.Include(p => p.Owner).First(p => p.ID == id);

            bool isOk = await TryUpdateModelAsync(pet);

            var validationErrors = ModelState.Values
                .Where(e => e.Errors.Count > 0)
                .SelectMany(e => e.Errors)
                .Select(e => e.ErrorMessage)
                .ToList();

            if(isOk)
            {
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        public IActionResult DeleteAjax(int id)
        {
            var existingPet = veterinaryManagerDbContext.Pets.Find(id);

            if (existingPet == null)
            {
                return NotFound();
            }

            veterinaryManagerDbContext.Pets.Remove(existingPet);
            veterinaryManagerDbContext.SaveChanges();

            // Return a JSON response indicating success for the AJAX call
            return Json(new { success = true });
        }

        public List<Pet> FilterPets(List<Pet> pets, PetFilterModel filterModel)
        {
            // Create a copy of the list to avoid modifying the original list
            var filteredPets = pets.ToList();

            // Apply filters based on the provided filter model properties
            if (!string.IsNullOrEmpty(filterModel.Name))
            {
                filteredPets = filteredPets.Where(pet => pet.Name.ToLowerInvariant().Contains(filterModel.Name.ToLowerInvariant())).ToList();
            }

            if (!string.IsNullOrEmpty(filterModel.OwnerName))
            {
                filteredPets = filteredPets.Where(pet => pet.Owner.FullName.ToLowerInvariant().Contains(filterModel.OwnerName.ToLowerInvariant())).ToList();
            }

            if (!string.IsNullOrEmpty(filterModel.Species))
            {
                filteredPets = filteredPets.Where(pet => pet.Species.ToLowerInvariant().Contains(filterModel.Species.ToLowerInvariant())).ToList();
            }

            return filteredPets;
        }

    }
}

veterinary.Web/Views/Shared/_Layout.cshtml
@using Veterinary.Model;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - veterinary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/veterinary.styles.css" asp-append-version="true" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"></script>

    <script src="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/js/bootstrap-datepicker.min.js"></script>

    <link id="bsdp-css" href="https://unpkg.com/bootstrap-datepicker@1.9.0/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="bg-primary border-bottom box-shadow text-white p-1">
            <div class="container-fluid d-flex justify-content-between">
                <a class="vet-logo" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/syringe.svg" class="fill-white"/>
                    <b style="color:white">Veterinary</b>
                </a>

                <div class="d-sm-inline-flex justify-content-between">

                    <ul class="flex-grow-1 d-flex gap-5 justify-content-between align-items-center mb-0">
                        <li>
                            <a class="text-white text-decoration-none" asp-route="Location">Location</a>

                        </li>

                        <li>
                            <a class="text-white text-decoration-none" asp-route="privacy">Privacy</a>
                        </li>

                        @if (User.IsInRole(RoleConstants.Doctor) || User.IsInRole(RoleConstants.Apprentice))
                        {
                            <li>
                                <a class="text-white text-decoration-none" asp-area="" asp-controller="Pet" asp-action="Index">Pets</a>
                            </li>

                            <li>
                                <a class="text-white text-decoration-none" asp-area="" asp-controller="Medication" asp-action="Index">Meds</a>
                            </li>

                            <li>
                                <a class="text-white text-decoration-none" asp-area="" asp-controller="Owner" asp-action="Index">Owners</a>
                            </li>

                        }
                    </ul>

                </div>

                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>

    <div class="pattern-background pt-5">
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - veterinary - <a class="text-white text-decoration-none" asp-route="privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>