veterinary.Web/Controllers/PetController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using Veterinary.DAL;
using Veterinary.Model;
using Veterinary.Web.Models;

namespace Veterinary.Web.Controllers
{
    public class PetController : BaseController
    {

        private VeterinaryManagerDbContext veterinaryManagerDbContext;
        private UserManager<AppUser> _userManager;

        public PetController(VeterinaryManagerDbContext veterinaryManagerDbContext, UserManager<AppUser> _userManager) :base(_userManager) { 
            this.veterinaryManagerDbContext = veterinaryManagerDbContext;
            this._userManager = _userManager;
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult Index()
        {
            var pets = veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .ToList();

            return View(pets.ToList());
        }


        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult IndexAjax(PetFilterModel petFilterModel)
        {
            var pets = veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .ToList();


            var filteredPets = FilterPets(pets, petFilterModel);

            return PartialView("_IndexTable", filteredPets.ToList());
        }

        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        [HttpPost]
        public IActionResult Filter(PetFilterModel petFilterModel)
        {
            var pets = veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .ToList();

            var filteredPets = FilterPets(pets, petFilterModel);

            return View("Index", pets.ToList());
        }


        [Authorize(Roles = RoleConstants.DoctorOrApprentice)]
        public IActionResult Details(int? id)
        {
            var pet = id != null ? veterinaryManagerDbContext.Pets
                .Include(p => p.Owner)
                .Include(p => p.Prescriptions)
                .Where(p => p.ID == id)
                .FirstOrDefault() : null;

            var prescriptions = veterinaryManagerDbContext.Prescriptions
                .Include(pr => pr.Medications)
                .Include(pr => pr.Pet)
                .Where(pr => pr.PetID == id)
                .ToList();

            ViewBag.Prescriptions = prescriptions.ToList();

            return View(pet);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        public IActionResult Create(string species)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();

            Pet pet;
            if(species == "Dog")
            {
                pet = new Dog();
            }
            else if(species == "Bird")
            {
                pet = new Bird();
            }
            else
            {
                pet = new Hamster();
            }

            return View(pet);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        public IActionResult CreateDog(Dog dog)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Pets.Add(dog);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(dog);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        public IActionResult CreateBird(Bird bird)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Pets.Add(bird);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(bird);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        public IActionResult CreateHamster(Hamster hamster)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();
            if (ModelState.IsValid)
            {
                veterinaryManagerDbContext.Pets.Add(hamster);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(hamster);
        }


        [Authorize(Roles = RoleConstants.Doctor)]
        [ActionName("Edit")]
        public IActionResult EditGet(int id)
        {
            ViewBag.Owners = veterinaryManagerDbContext.Owners.ToList();

            var pet = veterinaryManagerDbContext.Pets.First(p => p.ID == id);

            return View(pet);
        }


        [Authorize(Roles = RoleConstants.Doctor)]
        [HttpPost]
        [ActionName("Edit")]
        public async Task<IActionResult> EditPost(int id)
        {
            var pet = veterinaryManagerDbContext.Pets.Include(p => p.Owner).First(p => p.ID == id);

            bool isOk = await TryUpdateModelAsync(pet);

            var validationErrors = ModelState.Values
                .Where(e => e.Errors.Count > 0)
                .SelectMany(e => e.Errors)
                .Select(e => e.ErrorMessage)
                .ToList();

            if(isOk)
            {
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        public IActionResult DeleteAjax(int id)
        {
            var existingPet = veterinaryManagerDbContext.Pets.Find(id);

            if (existingPet == null)
            {
                return NotFound();
            }

            veterinaryManagerDbContext.Pets.Remove(existingPet);
            veterinaryManagerDbContext.SaveChanges();

            // Return a JSON response indicating success for the AJAX call
            return Json(new { success = true });
        }

        public List<Pet> FilterPets(List<Pet> pets, PetFilterModel filterModel)
        {
            // Create a copy of the list to avoid modifying the original list
            var filteredPets = pets.ToList();

            // Apply filters based on the provided filter model properties
            if (!string.IsNullOrEmpty(filterModel.Name))
            {
                filteredPets = filteredPets.Where(pet => pet.Name.ToLowerInvariant().Contains(filterModel.Name.ToLowerInvariant())).ToList();
            }

            if (!string.IsNullOrEmpty(filterModel.OwnerName))
            {
                filteredPets = filteredPets.Where(pet => pet.Owner.FullName.ToLowerInvariant().Contains(filterModel.OwnerName.ToLowerInvariant())).ToList();
            }

            if (!string.IsNullOrEmpty(filterModel.Species))
            {
                filteredPets = filteredPets.Where(pet => pet.Species.ToLowerInvariant().Contains(filterModel.Species.ToLowerInvariant())).ToList();
            }

            return filteredPets;
        }

    }
}

veterinary.Web/Controllers/PrescriptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Veterinary.DAL;
using Veterinary.Model;

namespace Veterinary.Web.Controllers
{
    public class PrescriptionController : BaseController
    {

        private VeterinaryManagerDbContext veterinaryManagerDbContext;
        private UserManager<AppUser> _userManager;

        public PrescriptionController(VeterinaryManagerDbContext veterinaryManagerDbContext, UserManager<AppUser> _userManager) : base(_userManager)
        {
            this.veterinaryManagerDbContext = veterinaryManagerDbContext;
            this._userManager = _userManager;
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        public IActionResult Create(int petid)
        {
            ViewBag.Medication = veterinaryManagerDbContext.Medication.ToList();
            ViewBag.PetID = petid;

            return View();
        }

        [Authorize(Roles = RoleConstants.Doctor)]

        [HttpPost]
        public IActionResult Create(Prescription prescription)
        {
            ViewBag.Medication = veterinaryManagerDbContext.Medication.ToList();

            if (ModelState.IsValid)
            {
                var selectedMedicationIds = Request.Form["Medications"];

                var prescriptionWithMeds = new Prescription
                {
                    Dosage = prescription.Dosage,
                    Diagnosis = prescription.Diagnosis,
                    Date = prescription.Date,
                    PetID = prescription.PetID,
                    Medications = selectedMedicationIds.Select(id => veterinaryManagerDbContext.Medication.Find(int.Parse(id))).ToList() // Eager loading of Medications
                };

                veterinaryManagerDbContext.Prescriptions.Add(prescriptionWithMeds);
                veterinaryManagerDbContext.SaveChanges();
                return RedirectToAction("Index","Pet");
            }

            return View(prescription);
        }

        [Authorize(Roles = RoleConstants.Doctor)]
        public IActionResult Delete(int id)
        {
            var existingPrescription = veterinaryManagerDbContext.Prescriptions.First(pr => pr.ID == id);

            if(existingPrescription == null)
            {
                return NotFound();
            }

            veterinaryManagerDbContext.Prescriptions.Remove(existingPrescription);
            veterinaryManagerDbContext.SaveChanges();

            return RedirectToAction("Details", "Pet", new { id = existingPrescription.PetID });
        }

    }
}

veterinary.Web/Views/Pet/Create.cshtml
@using Veterinary.Model
@model Pet

@{
    ViewData["Title"] = "Create";
}
<h1>@ViewData["Title"]</h1>


@if(Model.Species == "Dog")
{
    <form method="post" asp-controller="Pet" asp-action="CreateDog">
        <partial name="_CreateOrEdit" model="@Model" />
    </form>
}
else if(Model.Species == "Bird")
{
    <form method="post" asp-controller="Pet" asp-action="CreateBird">
        <partial name="_CreateOrEdit" model="@Model" />
    </form>
}
else if (Model.Species == "Hamster")
{
    <form method="post" asp-controller="Pet" asp-action="CreateHamster">
        <partial name="_CreateOrEdit" model="@Model" />
    </form>
}

veterinary.Web/Views/Pet/Details.cshtml
@using Veterinary.Model
@using Veterinary.Web

@{
    ViewData["Title"] = "Pet details";
}

<h1>@ViewData["Title"]</h1>



@if(Model == null)
{
    <div class="alert alert-danger">Pet not found.</div>
}
else
{
    


<div class="d-flex justify-content-between align-items-center">
    <h1 class="display-4">@Model.Name</h1>

    <a asp-controller="Pet" asp-action="Edit" asp-route-id="@Model.ID"><button class="btn btn-primary btn-lg px-5">Edit</button></a>
</div>
<hr />

<div class="row">
    <div class="col-md-6">
        <dl class="row">
            <dt class="col-sm-3">Species:</dt>
            <dd class="col-sm-9">@Model.Species</dd>
            <dt class="col-sm-3">Age:</dt>
            <dd class="col-sm-9">@Model.Age</dd>
            <dt class="col-sm-3">Birth Date:</dt>
            <dd class="col-sm-9">@Model.BirthDate.ToString("dd/MM/yyyy")</dd>
            <dt class="col-sm-3">Weight:</dt>
            <dd class="col-sm-9">@Model.Weight kg</dd>
            <dt class="col-sm-3">Owner:</dt>
            <dd class="col-sm-9">
                @if (@Model.Owner != null)
                {
                    <a>@Model.Owner.FullName</a>
                }
                else
                {
                    <span>No owner assigned</span>
                }
            </dd>
        </dl>
    </div>
    <div class="col-md-6">
        @if (Model is Dog)
        {
            <dl class="row">
                <dt class="col-sm-3">Breed:</dt>
                <dd class="col-sm-9"> @((Model as Dog).Breed)</dd>
            </dl>
        }
        else if (Model is Bird)
        {
        <dl class="row">
            <dt class="col-sm-3">Wingspan:</dt>
            <dd class="col-sm-9"> @((Model as Bird).Wingspan) cm</dd>
        </dl>
        }
        else if (Model is Hamster)
        {
        <dl class="row">
            <dt class="col-sm-3">Times Stepped On:</dt>
            <dd class="col-sm-9"> @((Model as Hamster).TimesSteppedOn)</dd>
        </dl>
        }
    </div>
</div>

<div class="card p-5">
    <div class="d-flex gap-1">
        <a asp-controller="Prescription" asp-action="Create" asp-route-petid="@Model.ID" class="w-100"><button class="btn btn-primary w-100">New prescription</button></a>
    </div>

    <partial name="../Prescription/_PrescriptionsTable" model="ViewBag.Prescriptions" />
</div>
}

veterinary.Web/Views/Pet/Edit.cshtml
@using Veterinary.Model
@model Pet

@{
    ViewData["Title"] = "Edit";
}
<h1>@ViewData["Title"]</h1>

<form asp-controller="Pet" asp-action="Edit">
    @Html.HiddenFor(p => p.ID)
    <partial name="_CreateOrEdit" model="Model"/>
</form>

veterinary.Web/Views/Pet/Index.cshtml
@using Veterinary.Model
@using Veterinary.Web.Models
@model List<Pet>

<div>
    <partial name="_PetFilter" model="new PetFilterModel()"/>
</div>

<div class="row card p-5">
    <div class="d-flex gap-1">
        <a asp-controller="Pet" asp-action="Create" asp-route-species="Dog" class="w-100"><button class="btn btn-primary w-100">Add Dog</button></a>
        <a asp-controller="Pet" asp-action="Create" asp-route-species="Bird" class="w-100"><button class="btn btn-primary w-100">Add Bird</button></a>
        <a asp-controller="Pet" asp-action="Create" asp-route-species="Hamster" class="w-100"><button class="btn btn-primary w-100">Add Hamster</button></a>
    </div>

    <div id="tableContainer">
        <partial name="_IndexTable" model="new List<Pet>()" />
    </div>
</div>

@section scripts {

    <script>
        // Ajax call to refresh the table

        $(document).ready(filterPets());

        function filterPets() {
            var formData = $("#petForm").serialize();
            
            $.ajax({
                url: "@Url.Action("IndexAjax", new PetFilterModel())",
                method: "POST",
                data: formData,
                success: function (html) {
                    $("#tableContainer").html(html)
                }
            })
        }

        function deletePet(petId) {
            $.ajax({
                url: '@Url.Action("DeleteAjax", "Pet")',
                method: "POST", 
                data: { id: petId }, 
                success: function (data) {
                    if (data.success === true) { 
                        filterPets(); // Refetch and update the table with AJAX
                    } else {
                        alert("Error deleting pet. Please try again."); 
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.error("Error deleting pet:", textStatus, errorThrown);
                   
                }
            });
        }

    </script>
}

veterinary.Web/Views/Pet/_CreateOrEdit.cshtml
@using Veterinary.Model
@model Pet

<div class="form-group">
    <label for="Species" class="col-form-label">Species:</label>

    <span>@Model.Species</span>  @Html.HiddenFor(m => m.Species)
</div>

<div id="dynamic-inputs">
    @* Common fields for all pets *@
    <div class="form-group">
        <label for="Name" class="col-form-label">Name:</label>

        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Enter pet name", required = true })

        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="form-group">
        <label for="BirthDate" class="col-form-label">Birth Date:</label>

        <div 
            class="input-group date" 
            data-provide="datepicker" 
            data-date-format="@System.Threading.Thread.CurrentThread.CurrentCulture.DateTimeFormat.ShortDatePattern.ToLower()"
        >
            <input asp-for="BirthDate" type="text" class="form-control datepicker" id="date">

            <div class="input-group-addon">
                <span class="glyphicon glyphicon-th"></span>
            </div>
        </div>
        <span class="text-danger" asp-validation-for="BirthDate"></span>
    </div>

    <div class="form-group">
        <label for="Weight" class="col-form-label">Weight (kg):</label>
        @Html.TextBoxFor(m => m.Weight, new { @class = "form-control", type = "number", step = "0.1", required = true })
        <span class="text-danger" asp-validation-for="Weight"></span>
    </div>

    <div class="form-group">
        <label for="OwnerID" class="col-form-label">Owner:</label>
        @Html.DropDownListFor(m => m.OwnerID, new SelectList(ViewBag.Owners, "ID", "FullName"),"", new { @class = "form-control", required = true })
        <span class="text-danger" asp-validation-for="OwnerID"></span>
    </div>

    @* Dynamic fields based on species *@
    <div>
        @if (Model.Species == "Dog")
        {
            <div class="form-group">
                <label for="Breed" class="col-form-label">Breed:</label>
                @Html.TextBoxFor(m => ((Dog)Model).Breed, new { @class = "form-control", placeholder = "Enter breed" })
            </div>
        }
        else if (Model.Species == "Bird")
        {
            <div class="form-group">
                <label for="Wingspan" class="col-form-label">Wingspan (cm):</label>
                @Html.TextBoxFor(m => ((Bird)Model).Wingspan, new { @class = "form-control", type = "number", step = "0.1" })
            </div>
        }
        else if (Model.Species == "Hamster")
        {
            <div class="form-group">
                <label for="TimesSteppedOn" class="col-form-control">Times Stepped On:</label>
                @Html.TextBoxFor(m => ((Hamster)Model).TimesSteppedOn, new { @class = "form-control", type = "number" })
            </div>
        }
    </div>
</div>

<button type="submit" class="btn btn-primary mt-5">Save</button>

veterinary.Web/Views/Pet/_IndexTable.cshtml
@using Veterinary.Model
@model List<Pet>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Animal</th>
            <th>Age</th>
            <th>Weight</th>
            <th>Owner</th>
            <th>Prescriptions</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var p in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Pet" asp-action="Details" asp-route-id="@p.ID">
                        @p.Name
                    </a>
                </td>

                <td>@p.Species</td>
                <td>@p.Age</td>
                <td>@p.Weight kg</td>
                <td>@p.Owner?.FullName</td>
                <td>@(p.Prescriptions?.Count ?? 0)</td>


                <td>
                    <button class="btn btn-danger" type="button" onclick="deletePet(@p.ID)">
                        <img src="/images/trash.svg" class="fill-white"/>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

veterinary.Web/Views/Pet/_PetFilter.cshtml
@using Veterinary.Web.Models
@model PetFilterModel

<div>

    <h5>Filter</h5>

    <form class="mb-2 d-flex gap-1" method="post" asp-controller="Pet" asp-action="Filter" id="petForm">
        <div class="d-flex gap-1 flex-grow-1">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Enter pet name" })

            @Html.TextBoxFor(m => m.OwnerName, new { @class = "form-control", placeholder = "Enter owner name" })

            @Html.TextBoxFor(m => m.Species, new { @class = "form-control", placeholder = "Enter species" })
        </div>
        <button type="button" onclick="filterPets()" class="btn btn-primary">Filter</button>
    </form>

</div>